{
 "title": "WATCHEDGE",
 "description": "cinghiali",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "CAMERAS MAP",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "watchedge",
     "rawSql": "SELECT \r\n  camera_id, \r\n  status,\r\n  ST_X(location_coordinates::geometry) AS latitude, \r\n  ST_Y(location_coordinates::geometry) AS longitude \r\nFROM camera;"
    }
   ]
  },
  {
   "title": "ONLINE VS OFFLINE CAMERAS",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "watchedge",
     "rawSql": "SELECT \r\n  status, \r\n  COUNT(camera_id) AS \"camera_count\" \r\nFROM camera \r\nGROUP BY status;"
    }
   ]
  },
  {
   "title": "BATTERY LEVEL UNDER 20%",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "watchedge",
     "rawSql": "SELECT \r\n  camera_id, \r\n  status, \r\n  battery_level \r\nFROM camera \r\nWHERE battery_level < 20 \r\nORDER BY battery_level ASC;"
    }
   ]
  },
  {
   "title": "DETECTIONS BY TIME OF DAY",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "watchedge",
     "rawSql": "SELECT\r\n  $__timeGroup(datasetstore.\"time\", '1h') AS \"time\",\r\n  animaldetected.animal_type AS \"metric\",\r\n  COUNT(animaldetected.detection_id) AS \"detections\"\r\nFROM animaldetected\r\nJOIN datasetstore ON animaldetected.event_id = datasetstore.event_id\r\n-- Notice that the WHERE clause is gone!\r\nGROUP BY 1, 2\r\nORDER BY 1;"
    }
   ]
  },
  {
   "title": "SPECIES DISTRIBUTION",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "dataset": "watchedge",
     "rawSql": "SELECT \r\n  animal_type, \r\n  COUNT(detection_id) AS \"total_detections\" \r\nFROM animaldetected \r\nGROUP BY animal_type \r\nORDER BY \"total_detections\" DESC;"
    }
   ]
  },
  {
   "title": "EDGE _DEVICE",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "dataset": "watchedge", "rawSql": "SELECT * FROM edge_device;" }
   ]
  },
  {
   "title": "CAMERA",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "dataset": "watchedge", "rawSql": "SELECT * FROM camera" }
   ]
  },
  {
   "title": "ANIMALDETECTED",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    { "dataset": "watchedge", "rawSql": "SELECT * FROM animaldetected;" }
   ]
  },
  {
   "title": "DATASETSTORE",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "dataset": "watchedge",
     "rawSql": "SELECT\r\n  *\r\nFROM\r\n  datasetstore"
    }
   ]
  }
 ]
}