services:
  postgresql:
    image: postgres
    container_name: edge-postgresql
    environment:
      POSTGRES_DB: gBOAR
      POSTGRES_USER: gBOAR
      POSTGRES_PASSWORD: gBOAR
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
      - ../../services/postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    restart: unless-stopped

  mosquitto:
    image: eclipse-mosquitto
    container_name: edge-mosquitto
    ports:
      - "1883:1883"
    volumes:
      - mosquitto-data:/mosquitto/data
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    restart: unless-stopped

volumes:
  pgdata:
  mosquitto-data:
