listener 1883
allow_anonymous true
persistence true
persistence_location /mosquitto/data/
log_dest stdout
log_type all

# Bridge to Cloud MQTT Broker
connection cloud-bridge
address cloud-mosquitto:1883
topic cloud/# out 1
topic cloud/+/+/cmd/upload in 1
cleansession false
notifications false
try_private true
start_type automatic
