listener 1883
allow_anonymous true
persistence true
persistence_location /mosquitto/data/
log_dest stdout
log_type all

# Edge -- Cloud MQTT Bridge
connection cloud-bridge
### CHANGE-ME: Update the address to point to cloud MQTT broker.
address 192.168.178.20:1884
topic cloud/# out 1
topic cloud/+/+/cmd/upload in 1
cleansession false
notifications false
try_private true
start_type automatic
