services:
  cloud-mosquitto:
    image: eclipse-mosquitto
    container_name: cloud-mosquitto
    ports:
      - "1884:1883"
    volumes:
      - cloud-mosquitto-storage:/mosquitto/data
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    networks:
      - cloud-network
    healthcheck:
      test: [ "CMD-SHELL", "mosquitto_sub -t '$$SYS/broker/version' -C 1 > /dev/null" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  cloud-postgresql:
    build:
      context: ../../services/database-postgresql/docker-postgis/17-3.5
    image: watchedge-postgis
    container_name: cloud-postgresql
    environment:
      POSTGRES_DB: watchedge-db
      POSTGRES_USER: watchedge
      POSTGRES_PASSWORD: watchedge
    volumes:
      - cloud-postgresql-storage:/var/lib/postgresql
      - ../../services/database-postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - cloud-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U watchedge -d watchedge-db" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  cloud-rustfs-init:
    image: alpine
    container_name: cloud-rustfs-init
    volumes:
      - cloud-rustfs-storage:/data
    command: >
      sh -c "
        chown -R 10001:10001 /data &&
        echo 'Volume permissions fixed' &&
        exit 0
      "
    restart: "no"

  cloud-rustfs:
    image: rustfs/rustfs
    container_name: cloud-rustfs
    security_opt:
      - "no-new-privileges:true"
    environment:
      RUSTFS_VOLUMES: /data/rustfs
      RUSTFS_ADDRESS: 0.0.0.0:9000
      RUSTFS_CONSOLE_ADDRESS: 0.0.0.0:9001
      RUSTFS_CONSOLE_ENABLE: "true"
      RUSTFS_ACCESS_KEY: watchedge
      RUSTFS_SECRET_KEY: watchedge
    ports:
      - "9002:9000"
      - "9003:9001"
    volumes:
      - cloud-rustfs-storage:/data/rustfs
    networks:
      - cloud-network
    depends_on:
      cloud-rustfs-init:
        condition: service_completed_successfully
    healthcheck:
      test: [ "CMD", "sh", "-c", "curl -f http://127.0.0.1:9000/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  cloud-processing-service:
    build:
      context: ../../services/processing-service
    image: watchedge-processing-service
    container_name: cloud-processing-service
    environment:
      SERVICE_MODE: CLOUD
      MQTT_HOST: cloud-mosquitto
      MQTT_PORT: 1883
      DATABASE_URL: postgresql://watchedge:watchedge@cloud-postgresql:5432/watchedge-db
      ### CHANGE-ME: Change to reachable FQDN/IP (needs to be reachable by both Edge and Cloud) when running in production.
      OBJECT_STORAGE_URL: http://192.168.178.20:9002
      S3_ACCESS_KEY: watchedge
      S3_SECRET_KEY: watchedge
      S3_BUCKET: watchedge-images
      MQTT_CLIENT_ID: cloud-processing-service
      ### CHANGE-ME: Change to reachable FQDN/IP (needs to be reachable by both Edge and Cloud) when running in production.
      WEB_BASE_URL: http://192.168.178.20:8001
    ports:
      - "8001:8000"
    networks:
      - cloud-network
    depends_on:
      cloud-mosquitto:
        condition: service_healthy
      cloud-postgresql:
        condition: service_healthy
      cloud-rustfs:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", 'python -c ''import urllib.request; urllib.request.urlopen("http://127.0.0.1:8000/health")''' ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  cloud-grafana:
    image: grafana/grafana
    container_name: cloud-grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: watchedge
      GF_SECURITY_ADMIN_USER: watchedge
      GF_INSTALL_PLUGINS: grafana-postgresql-datasource
      GF_CONFIG_DB_URL: cloud-postgresql:5432
      GF_CONFIG_DB_USER: watchedge
      GF_CONFIG_DB_PASSWORD: watchedge
      GF_CONFIG_DB_NAME: watchedge-db
    ports:
      - "3001:3000"
    volumes:
      - cloud-grafana-storage:/var/lib/grafana
      - ../../services/dashboard-grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ../../services/dashboard-grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ../../services/dashboard-grafana/dashboard_model.json:/var/lib/grafana/dashboards/dashboard_model.json:ro
    networks:
      - cloud-network
    depends_on:
      cloud-postgresql:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://127.0.0.1:3000/api/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

volumes:
  cloud-postgresql-storage:
  cloud-mosquitto-storage:
  cloud-rustfs-storage:
  cloud-grafana-storage:


networks:
  cloud-network:
    name: cloud-network
