{
 "title": "ItalTel Tech 3.0",
 "time": { "from": "2026-02-21T11:15:27.316Z", "to": "2026-02-22T11:15:27.316Z" },
 "panels": [
  {
   "title": "Edge Device",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "dataset": "watchedge-db",
     "rawSql": "SELECT COUNT(edge_id) FROM edge_device LIMIT 50 "
    }
   ]
  },
  {
   "title": "Camera",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "watchedge-db",
     "rawSql": "SELECT COUNT(camera_id) FROM camera LIMIT 50 "
    }
   ]
  },
  {
   "title": "Events",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 14, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "watchedge-db",
     "rawSql": "SELECT COUNT(event_id) FROM datasetstore LIMIT 50 "
    }
   ]
  },
  {
   "title": "Edge Device",
   "type": "table",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 5 },
   "targets": [
    {
     "dataset": "watchedge-db",
     "rawSql": "SELECT * FROM edge_device LIMIT 50 "
    }
   ]
  },
  {
   "title": "Camera",
   "type": "table",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 5 },
   "targets": [
    { "dataset": "watchedge-db", "rawSql": "SELECT * FROM camera LIMIT 50 " }
   ]
  },
  {
   "title": "Events",
   "type": "table",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 5 },
   "targets": [
    {
     "dataset": "watchedge-db",
     "rawSql": "SELECT * FROM datasetstore LIMIT 50 "
    }
   ]
  },
  {
   "title": "Animals",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "watchedge-db",
     "rawSql": "SELECT COUNT(detection_id) FROM animaldetected LIMIT 50 "
    }
   ]
  },
  {
   "title": "Animals",
   "type": "table",
   "gridPos": { "h": 20, "w": 14, "x": 10, "y": 12 },
   "targets": [
    {
     "dataset": "watchedge-db",
     "rawSql": "SELECT * FROM animaldetected LIMIT 50 "
    }
   ]
  }
 ]
}