apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    uid: efe10tuc9mlmof
    url: edge-postgresql:5432
    user: gBOAR
    secureJsonData:
      password: gBOAR
    jsonData:
      database: gBOAR
      sslmode: "disable"
      postgresVersion: 15
    access: proxy
    isDefault: true
