apiVersion: 1

datasources:
  - name: PostgreSQL
    type: grafana-postgresql-datasource
    uid: bfejnp2moiyo0d
    url: cloud-postgresql:5432
    user: watchedge
    secureJsonData:
      password: watchedge
    jsonData:
      database: watchedge-db
      sslmode: "disable"
      postgresVersion: 15
    access: proxy
    isDefault: true
